name: run-eslint

on:
  pull_request:
    types: [opened] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modelues
        run: npm i
      - name: Run ESLint
        run: npm run lint
